app:
  name: crud_mahasiswa
  port: ":4040"

db:
  host: localhost
  port: 5432
  name: crud_mahasiswa
  user: postgres
  password: mh217512
  connection_pool:
    max_idle_connection: 10
    max_open_connection: 30
    max_lifetime_connection: 60 #second
    max_idletime_connection: 60 #second